@HelpDesk.Api_HostAddress = http://localhost:5011

###

GET {{HelpDesk.Api_HostAddress}}/api/tickets

###

POST {{HelpDesk.Api_HostAddress}}/api/tickets
Content-Type: application/json

{
  "title": "Laptop cannot connect to Wi-Fi",
  "description": "The employee cannot connect to the office network.",
  "priority": "High",
  "status": "Open"
}

###

GET {{HelpDesk.Api_HostAddress}}/api/tickets/1

###

PUT {{HelpDesk.Api_HostAddress}}/api/tickets/1
Content-Type: application/json

{
  "title": "Laptop cannot connect to Wi-Fi",
  "description": "The issue appears to be related to the network adapter.",
  "priority": "Critical",
  "status": "In Progress"
}

###

DELETE {{HelpDesk.Api_HostAddress}}/api/tickets/1